### ISSUE TITLE
Исправить верстку в общей таблице

### ISSUE THREAD

**Issue by g-arslan** [petuhovskiy/ejudge-app#9]
![image](https://user-images.githubusercontent.com/5970594/53489417-2ddbc000-3aa2-11e9-99e9-f0fbb63ed4ad.png)
Когда этих статусов больше двух таблица наезжает на них. (У нас забаговался один ран и статусов постоянно три)

**Comment by petuhovskiy** [comment]
Fixed in https://github.com/mikkerlo/ejudge-app/commit/ab3e6c651417e6765dafe5dc0150659daad63d96
